package com.boclips.users.config.security

object UserRoles {
    const val ROLE_API = "API"
    const val ROLE_TEACHER = "TEACHER"
    const val ROLE_BOCLIPS_SERVICE = "BOCLIPS_SERVICE"

    const val INSERT_CONTRACTS = "INSERT_CONTRACTS"
    const val VIEW_CONTRACTS = "VIEW_CONTRACTS"
    const val UPDATE_CONTRACTS = "UPDATE_CONTRACTS"

    const val VIEW_USERS = "VIEW_USERS"

    const val INSERT_ORGANISATIONS = "INSERT_ORGANISATIONS"
    const val VIEW_ORGANISATIONS = "VIEW_ORGANISATIONS"
    const val UPDATE_ORGANISATIONS = "UPDATE_ORGANISATIONS"

    const val SYNCHRONIZE_USERS_KEYCLOAK = "SYNCHRONIZE_USERS_KEYCLOAK"
    const val SYNCHRONIZE_USERS_HUBSPOT = "SYNCHRONIZE_USERS_HUBSPOT"
}
