package com.boclips.users.api.response.feature

typealias FeaturesResource = Map<String, Boolean>

enum class FeatureKeyResource {
    LTI_SLS_TERMS_BUTTON,
    LTI_RESPONSIVE_VIDEO_CARD,
    LTI_AGE_FILTER,
    TEACHERS_HOME_BANNER,
    TEACHERS_HOME_SUGGESTED_VIDEOS,
    TEACHERS_HOME_PROMOTED_COLLECTIONS,
    TEACHERS_SUBJECTS,
    USER_DATA_HIDDEN,
    BO_WEB_APP_COPY_OLD_LINK_BUTTON,
    BO_WEB_APP_ADDITIONAL_SERVICES,
    BO_WEB_APP_PRICES
}
