#!/usr/bin/env bash

echo "KEYCLOAK_USERNAME: $(lpass show --username "e2e-admin-testing")" > contract-test-setup.yml
echo "KEYCLOAK_PASSWORD: $(lpass show --password "e2e-admin-testing")" >> contract-test-setup.yml