#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"
cat > "$cwd/contract-test-setup.yml" <<EOF
KEYCLOAK_USERNAME: $(get-k8s-concourse-secret boclips testing-keycloak user-service-account-username)
KEYCLOAK_PASSWORD: $(get-k8s-concourse-secret boclips testing-keycloak user-service-account-password)
HUBSPOT_API_KEY: $(get-k8s-secret testing user-service HUBSPOT_API_KEY)
EOF
