#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"
output="$cwd/contract-test-setup.yml"

echo "KEYCLOAK_USERNAME: $(get-k8s-concourse-secret boclips keycloak user-service-account-username)"            > "$output"
echo "KEYCLOAK_PASSWORD: $(get-k8s-concourse-secret boclips keycloak user-service-account-password)"            >> "$output"
echo "HUBSPOT_API_KEY: $(decoded-secret user-service testing | jq -r '.HUBSPOT_API_KEY')"   >> "$output"
