#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"
cat > "$cwd/contract-test-setup.yml" <<EOF
KEYCLOAK_USERNAME: $(bo show credential concourse-main boclips.testing-keycloak user-service-account-username)
KEYCLOAK_PASSWORD: $(bo show credential concourse-main boclips.testing-keycloak user-service-account-password)
HUBSPOT_API_KEY: $(bo show credential testing user-service HUBSPOT_API_KEY)
EOF
